# Use root/example as user/password credentials
version: '3.1'

services:
  react-app:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    stdin_open: true
    command: npm start
    ports: 
     - "3000:3000"
    depends_on:
      - express-server

  proxy:
    image: dperson/torproxy
  
  # elasticsearch:
  #   image: elasticsearch
  #   ports: 
  #     - "9200:9200"

  express-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - proxy


networks:
  mern-app: 
    driver: local