# Use root/example as user/password credentials
version: '3.1'

services:
  react-app:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    stdin_open: true
    command: npm start
    ports: 
     - "3000:3000"
    depends_on:
      - express-server
    volumes:
      - '/usr/app/client/node_modules'
      - ./client:/usr/app/client
    environment:
      - "TZ=Israel" 

  proxy:
    container_name: proxy 
    image: dperson/torproxy
  

  express-server:
    container_name: server 
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - '/usr/app/server/node_modules'
      - ./server:/usr/app/server"
    environment:
      - "TZ=Israel" 


networks:
  mern-app: 
    driver: local