# Use root/example as user/password credentials
version: '3.1'

services:
  react-app:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    stdin_open: true
    command: npm start
    ports: 
     - "3000:3000"
    depends_on:
      - express-server

  # tor-privoxy:
  #   restart: always
  #   image: dockage/tor-privoxy:latest
  #   ports:
  #     - "9050:9050" # Tor proxy
  #     - "9051:9051" # Tor control port
  #     - "8118:8118" # Privoxy
  proxy:
    image: dperson/torproxy
    # ports:
    #   - "8118:8118" # dperson/torproxy
    #   - "9050:9050" # Tor proxy
      # - "9051:9051" # Tor control port

  express-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - proxy


networks:
  mern-app: 
    driver: local